config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :usuarios, only: [:index, :show, :new, :create, :edit, :update]
  root 'usuarios#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/usuario.rb
class Usuario
    include ActiveModel::Model
  
    attr_accessor :id, :nombre, :email, :created_at, :updated_at

    BASE_URL = "http://127.0.0.1:3000/usuarios"

    def self.all
        response = RestClient.get(BASE_URL)
        JSON.parse(response.body)
    rescue RestClient::ExceptionWithResponse => e
        raise "Error al obtener usuarios: #{e.response}"
    end

    def self.find(id)
        response = RestClient.get("#{BASE_URL}/#{id}")in
        JSON.parse(response.body)
    rescue RestClient::ExceptionWithResponse => e
        raise "Error al obtener usuario: #{e.response}"
    end

    def self.create(params)
        response = RestClient.post(BASE_URL, params.to_json, {content_type: :json, accept: :json})
        response.code == 201
        JSON.parse(response.body)
    rescue RestClient::ExceptionWithResponse => e
        raise "Error al crear usuario: #{e.response}"
    end

    def update(params)
        response = RestClient.patch("#{BASE_URL}/#{id}", params.to_json, {content_type: :json, accept: :json})
        if response.code == 200
            attributes = JSON.parse(response.body)
            self.attributes = attributes
            true
          else
            false
        end
    rescue RestClient::ExceptionWithResponse => e
        raise "Error al actualizar usuario: #{e.response}"
    end
    
    def self.destroy(id)
        response = RestClient.delete("#{BASE_URL}/#{id}")
        response.code == 204
    rescue RestClient::ExceptionWithResponse => e
        raise "Error al eliminar usuario: #{e.response}"
    end

    # Método para establecer los atributos del modelo
    def attributes=(attrs)
        attrs.each do |key, value|
        send("#{key}=", value)
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
    def index
        @usuarios = Usuario.all
    end
  
    def show
        @usuario = Usuario.find(params[:id])
    end
  
    def new
        @usuario = Usuario.new
    end
  
    def create
        @usuario = Usuario.create(usuario_params)
        if @usuario.persisted?
        redirect_to usuarios_path, notice: 'Usuario creado exitosamente.'
        else
        render :new
        end
    end
  
    def edit
        @usuario = Usuario.find(params[:id])
    end
  
    def update
        @usuario = Usuario.find(params[:id])
        if @usuario.update(usuario_params)
        redirect_to usuario_path(@usuario.id), notice: 'Usuario actualizado exitosamente.'
        else
        render :edit
        end
    end
  
    def destroy
        if Usuario.destroy(params[:id])
            flash[:success] = "Usuario eliminado con éxito"
        else
            flash[:error] = "Error al eliminar usuario"
        end
        redirect_to usuarios_path
    end
  
    private
  
    def usuario_params
        params.require(:usuario).permit(:nombre, :email, :edad)
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Consumo Api" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/_form.html.erb
<!-- _form.html.erb -->
<%= form_with model: @usuario, url: form_url, method: form_method do |f| %>
  <div>
    <%= f.label :nombre, 'Nombre' %><br>
    <%= f.text_field :nombre %>
  </div>

  <div>
    <%= f.label :correo, 'Email' %><br>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<!-- edit.html.erb -->
<h1>Editar Usuario</h1>
<%= render 'form', form_url: usuario_path(@usuario["id"]), form_method: :patch %>
<%= link_to 'Volver a la lista', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Lista de Usuarios</h1>

    <table>
    <thead>
        <tr>
        <th>Nombre</th>
        <th>Email</th>
        <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <% @usuarios.each do |usuario| %>
        <tr>
            <td><%= usuario['nombre'] %></td>
            <td><%= usuario['correo'] %></td>
            <td>
            <%= link_to 'Mostrar', usuario_path(usuario['id']) %>
            <%= link_to 'Editar', edit_usuario_path(usuario['id']) %>
            <%= link_to 'Eliminar', usuario_path(usuario['id']), method: :delete, data: { confirm: '¿Estás seguro?' } %>
            </td>
        </tr>
        <% end %>
    </tbody>
    </table>

<%= link_to 'Crear nuevo usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<!-- new.html.erb -->
<h1>Nuevo Usuario</h1>
<%= render 'form', form_url: usuarios_path, form_method: :post %>
<%= link_to 'Volver a la lista', usuarios_path %>

app/views/usuarios/show.html.erb
<h1>Detalles del Usuario</h1>

<p><strong>Nombre:</strong> <%= @usuario["nombre"] %></p>
<p><strong>Email:</strong> <%= @usuario["correo"] %></p>

<%= link_to 'Editar', edit_usuario_path(@usuario["id"]) %> |
<%= link_to 'Eliminar', usuario_path(@usuario["id"]), method: :delete, data: { confirm: '¿Estás seguro de eliminar este usuario?' } %> |
<%= link_to 'Volver a la lista', usuarios_path %>